[package]
name = "securecompare-leaderboard-wasm"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
lto = true

[profile.wasm]
inherits = "release"
lto = true
panic = "abort"
codegen-units = 1

[dependencies]
rand_chacha = "0.3"
securecompare-leaderboard-crypto = { path = "../../rust/leaderboard-crypto" }
wasm-bindgen = "0.2"
